services: 
  # Alpine services
  demoapi-alpine:
    image: demoapi:alpine
    build:
      context: .
      dockerfile: Alpine/Dockerfile-alpine
    container_name: demoapi-alpine
    ports:
      - 5001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-alpine-trimmed:
    image: demoapi:alpine-trimmed
    build:
      context: .
      dockerfile: Alpine/Dockerfile-alpine-trimmed
    container_name: demoapi-alpine-trimmed
    ports:
      - 5002:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-alpine-aot:
    image: demoapi:alpine-aot
    build:
      context: .
      dockerfile: Alpine/Dockerfile-alpine-aot
    container_name: demoapi-alpine-aot
    ports:
      - 5003:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-alpine-extra:
    image: demoapi:alpine-extra
    build:
      context: .
      dockerfile: Alpine/Dockerfile-alpine-extra
    container_name: demoapi-alpine-extra
    ports:
      - 5004:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  # CBL Mariner services
  demoapi-cbl-mariner:
    image: demoapi:cbl-mariner
    build:
      context: .
      dockerfile: CBL-Mariner/Dockerfile-cbl-mariner
    container_name: demoapi-cbl-mariner
    ports:
      - 5011:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-cbl-mariner-distroless-trimmed:
    image: demoapi:cbl-mariner-distroless-trimmed
    build:
      context: .
      dockerfile: CBL-Mariner/Dockerfile-cbl-mariner-distroless-trimmed
    container_name: demoapi-cbl-mariner-distroless-trimmed
    ports:
      - 5012:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-cbl-mariner-distroless-aot:
    image: demoapi:cbl-mariner-distroless-aot
    build:
      context: .
      dockerfile: CBL-Mariner/Dockerfile-cbl-mariner-distroless-aot
    container_name: demoapi-cbl-mariner-distroless-aot
    ports:
      - 5013:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-cbl-mariner-distroless-extra:
    image: demoapi:cbl-mariner-distroless-extra
    build:
      context: .
      dockerfile: CBL-Mariner/Dockerfile-cbl-mariner-distroless-extra
    container_name: demoapi-cbl-mariner-distroless-extra
    ports:
      - 5014:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
        
  # Ubuntu services
  demoapi-jammy:
    image: demoapi:jammy
    build:
      context: .
      dockerfile: Ubuntu/Dockerfile-jammy
    container_name: demoapi-jammy
    ports:
      - 5021:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-jammy-chiseled-trimmed:
    image: demoapi:jammy-chiseled--trimmed
    build:
      context: .
      dockerfile: Ubuntu/Dockerfile-jammy-chiseled-trimmed
    container_name: demoapi-jammy-chiseled-trimmed
    ports:
      - 5022:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-jammy-chiseled-aot:
    image: demoapi:jammy-chiseled-aot
    build:
      context: .
      dockerfile: Ubuntu/Dockerfile-jammy-chiseled-aot
    container_name: demoapi-jammy-chiseled-aot
    ports:
      - 5023:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  demoapi-jammy-chiseled-extra:
    image: demoapi:jammy-chiseled-extra
    build:
      context: .
      dockerfile: Ubuntu/Dockerfile-jammy-chiseled-extra
    container_name: demoapi-jammy-chiseled-extra
    ports:
      - 5024:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  

