FROM mcr.microsoft.com/dotnet/sdk:8.0-cbl-mariner2.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish DemoApi.csproj -c Release -o /app -r linux-x64
RUN rm /app/*.pdb /app/*.Development.json

FROM mcr.microsoft.com/dotnet/aspnet:8.0-cbl-mariner2.0 AS final
WORKDIR /app
COPY --from=build /app .
USER $APP_UID
ENTRYPOINT ["./DemoApi"]
