FROM mcr.microsoft.com/dotnet/nightly/sdk:8.0-cbl-mariner2.0-aot AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -r linux-x64 -o /app DemoApiAot.csproj
RUN rm /app/*.dbg /app/*.Development.json

FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-cbl-mariner2.0-distroless-extra AS final
WORKDIR /app
COPY --from=build /app .
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
USER $APP_UID
ENTRYPOINT ["./DemoApiAot"]
